services:
  keyvaluestore:
    container_name: drew-raft
    image: keyvaluestore
    build:
      context: .
      dockerfile: KeyValueStore/Dockerfile
    ports:
      - "4322:8080"
    networks:
      - drew-raft-network
    restart: unless-stopped

networks:
  drew-raft-network:
    external: true